FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3-pip 
	
RUN pip3 install pytenable pydantic pandas python-dotenv openpyxl click

ENV PATH "$PATH:/usr/bin/env/:/usr/src/app"

COPY .env cli.py workbooks.py io_config_tags.py generate_password.py tio-config.xlsx /usr/src/app/

WORKDIR /usr/src/app

# RUN chmod +x cli.py

ENTRYPOINT ["python3", "cli.py", "load", "tio-config.xlsx", "users"]
